name: ci-lint

on:
  pull_request:
    branches: [main]

jobs:
  ci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Install fonts
        run: |
          sudo apt install fonts-noto-core -y

      - name: Yarn
        run: |
          yarn install --frozen-lockfile

      - name: Mermaid diagrams synced with sources
        run: |
          yarn diagrams
          git diff --submodule=diff --exit-code
